<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TuinRTX-Setup</AssemblyName>
    <RootNamespace>TuinRTX.Installer</RootNamespace>
    <ApplicationIcon>TuinRTX.ico</ApplicationIcon>
    <Version>1.0.5</Version>
    <Product>TuinRTX Setup</Product>
    <Company>TuinRTX Project</Company>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="art\*.jpg" />
  </ItemGroup>
</Project>
